feat(git): Add `[skip ci]` to conflicting cherry-picks
nextcloud/backportbot pull request #378
Opened 2023-04-04 06:46 UTC by ChristophWurst

Fixes https://github.com/nextcloud/backportbot/issues/361

A backport can run through three scenarios
1) Cherry-pick passes -> :sunglasses: 
2) Cherry-pick fails but passes with --strategy-option=ours -> troublesome PR -> skip CI
3) Cherry-pick fails with both strategies -> no PR, no CI

The changes are fully untested. Review with care.

2023-04-04 06:50 UTC, skjnldsv approved these changes

2023-04-11 11:00 UTC, st3iny requested changes
I tried to test some bits locally in the node REPL.

2023-04-11 11:04 UTC, st3iny commented on lib/git.js
> +            to: commits[i],
```suggestion
            to: `${commits[0]}~1`,
```

The syntax `COMMIT_HASH~1` means 1 commit after COMMIT_HASH (which itself is not included). Now, a single commit is returned (`commits['i']`).

2023-04-11 11:05 UTC, st3iny commented on lib/git.js
> +            to: commits[i],
Otherwise, `git.log()` will just return an empty log: `ListLogSummary { all: [], latest: null, total: 0 }`

2023-04-12 07:21 UTC, st3iny approved these changes
:fist_oncoming: :wood:

2023-04-13 07:28 UTC, merged